name: Build manifest.json

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: read-all

jobs:
    
  build:

    permissions:
      contents: read
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Repository info
      run: echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
    - name: Github actions runid
      run: echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
    - name: Runner info
      run: echo "$RUNNER_NAME on $RUNNER_OS($RUNNER_ARCH)"
    - name: test env
      run: echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
    - name: test env
      run: echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
    - name: test env
      run: echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
    - name: test env
      run: echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
    - name: test env
      run: echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
    - name: test env
      run: echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
