name: Build manifest.json

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: read-all

env:
  on-dev: true
  alt-branch-name: manifestjson

jobs:

  build:

    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/stale@v5

    - name: Github Repository info
      run: |
        echo "Github repository:             $GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
        echo "Github repository runner-id:   $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        echo "Github repository runner-name: $RUNNER_NAME on $RUNNER_OS($RUNNER_ARCH)"
        echo "Github API URL:                $GITHUB_API_URL/repos/$GITHUB_REPOSITORY"

    - name: "[GithubAPI] Remaining API Rate"
      run: |
        curl -H 'Content-Type: Application/json' https://api.github.com/rate_limit | jq

    - name: local repository update
      run: |
        set -x
        git fetch
        git pull
        git status

    - name: Create Branch
      run: |
        set -x
        git branch -r
        git branch ${{ env.alt-branch-name }}
        git checkout ${{ env.alt-branch-name }}
        git branch --set-upstream-to=origin/${{ env.alt-branch-name }} ${{ env.alt-branch-name }}
        git status

    - name: git config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "github-actions[bot]"

    - name: Github Repository info
      run: |
        curl -H 'Content-Type: Application/json' $GITHUB_API_URL/repos/$GITHUB_REPOSITORY | jq .name
        curl -H 'Content-Type: Application/json' $GITHUB_API_URL/repos/$GITHUB_REPOSITORY | jq .description

    - name: Update Manifest file
      run: php .github/workflows/build-manifest-json.php

    - name: Check git status
      run: git status

    - name: Commit 
      run: |
        git status
        git add -A
        git commit -m 'Auto commit - Github Actions[bot]'
        git push

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: Update Manifest file
        title: Auto PR - Update Manifest file
        body: Auto PR - Update Manifest file
        labels: bot
        base: master
        branch: ${{ env.alt-branch-name }}
        delete-branch: true
