name: Create the Favicon

on:
    workflow_dispatch:
    push:

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v4

            - run: wget https://github.com/n138-kz.png

            - run: ls -lh n138-kz.png

            - run: file n138-kz.png

            - run: od n138-kz.png

            - run: docker run --name ubuntu --platform linux/amd64 --mount type=bind,source=./,target=/media -w /media -d -i ubuntu /bin/bash -c 'while :;do uname -a; done'

            - run: docker inspect ubuntu

            - run: docker exec ubuntu apt-get -y update

            - run: docker exec ubuntu apt-get -y install ffmpeg
