name: check the dns

on:
    workflow_dispatch:
    push:

permissions:
    contents: read

jobs:
    n138_jp:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                ref: main

            - run: nslookup n138.jp
            - run: dig n138.jp in soa
            - run: dig n138.jp in ns
            - run: dig n138.jp in a
            - run: dig n138.jp in aaaa
            - run: dig n138.jp in cname
            - run: dig n138.jp in txt
            - run: dig n138.jp in srv
