name: GITHUB Action

on:
  workflow_dispatch:
  workflow_call:

env:
  check_ok: true
  docker_credential_username: ${{ vars.docker_credential_username }}
  docker_credential_password: ${{ secrets.docker_credential_password }}

permissions:
  contents: read

jobs:
  check_var:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: env.docker_credential_username
        if: ${{ env.docker_credential_username == '' }}
        run: |
          echo 'check_ok=false' >> $GITHUB_ENV;
          echo '::error title=Error::Require and Has NOT Set:`docker_credential_username`';

      - name: env.docker_credential_password
        if: ${{ env.docker_credential_password == '' }}
        run: |
          echo 'check_ok=false' >> $GITHUB_ENV;
          echo '::error title=Error::Require and Has NOT Set:`docker_credential_password`';

      - name: check ok?
        if: ${{ ! env.check_ok }}
        run: exit 1

  do_action:
    runs-on: ubuntu-latest
    needs: check_var
    steps:
      - uses: actions/checkout@v4

      - name: docker login
        run: docker login --username ${{ env.docker_credential_username }} --password ${{ env.docker_credential_password }}

      - name: Display the URL
        run: echo '::notice title=URL::https://hub.docker.com/u/${{ vars.docker_credential_username }}'
