name: GITHUB Action

on:
  workflow_dispatch:
    inputs:
      gh_actor_message:
        default: Test RUN
        required: true
        description: Actor message
        type: string
  workflow_call:

env:
  check_ok: true
  discord_avatar_url: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png
  discord_username: Github-Actions
  discord_webhook_url: ${{ secrets.discord_webhook_url }}
  github_actor_message: ""
  github_workflow_ref_name: ${{ github.workflow_ref }}

permissions:
  contents: read

jobs:
  check_var:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: env.discord_avatar_url
        if: ${{ env.discord_avatar_url == '' }}
        run: |
          echo '::error title=Error::Require and Has NOT Set:`discord_avatar_url`';
          echo 'check_ok=false' >> $GITHUB_ENV;

      - name: env.discord_username
        if: ${{ env.discord_username == '' }}
        run: |
          echo '::error title=Error::Require and Has NOT Set:`discord_username`';
          echo 'check_ok=false' >> $GITHUB_ENV;

      - name: env.discord_webhook_url
        if: ${{ env.discord_webhook_url == '' }}
        run: |
          echo '::error title=Error::Require and Has NOT Set:`discord_webhook_url`';
          echo 'check_ok=false' >> $GITHUB_ENV;

      - name: check ok?
        if: ${{ ! env.check_ok }}
        run: exit 1

  do_action:
    runs-on: ubuntu-latest
    needs: check_var
    steps:
      - uses: actions/checkout@v4

      - name: Actor message(type=workflow_dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          gh_actor_message='${{ inputs.gh_actor_message }}';
          echo 'github_actor_message='${gh_actor_message} >> $GITHUB_ENV;
          echo '::notice title=Actor message::'${gh_actor_message};

      - name: Actor message(type=push)
        if: ${{ github.event_name == 'push' }}
        run: |
          gh_actor_message='${{ toJSON(github.event.commits) }}';
          gh_actor_message=$(echo ${gh_actor_message} | jq -r .[0].message);
          gh_actor_message=${gh_actor_message%\\n*};
          gh_actor_message=${gh_actor_message}' #'${{ github.run_number }};
          echo 'github_actor_message='${gh_actor_message} >> $GITHUB_ENV;
          echo '::notice title=Actor message::'${gh_actor_message};
    
      - name: GITHUB Context
        run: |
          echo '{"env": [{"github": ${{ toJSON(github) }}}, {"secrets": ${{ toJSON(secrets) }}}]}' | jq | tee github-action-run_$(echo '${{ github.repository }}' | sed -e 's#/#_#g')_github-context.json;

      - name: GITHUB RestAPI /repos
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }} | jq | tee github-action-run_$(echo '${{ github.repository }}' | sed -e 's#/#_#g')_github-repos.json;
    
      - name: workflow_ref
        run: |
          gh_workflow_ref='${{ github.workflow_ref }}';
          gh_workflow_ref=${gh_workflow_ref#*workflows/};
          gh_workflow_ref=${gh_workflow_ref%@*};
          echo 'github_workflow_ref_name='${gh_workflow_ref} >> $GITHUB_ENV;

      - name: Send Discord
        if: ${{ false }}
        run: |
          for f in github-action-run*; do \
            curl -X POST \
              -H 'Content-Type:multipart/form-data' \
              -F 'avatar_url=${{ env.discord_avatar_url }}' \
              -F 'username=${{ env.discord_username }}' \
              -F 'file=@'${f} \
              -F $'content=Launched github action: [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}/actions/workflows/${{ env.github_workflow_ref_name }}).\n${{ github.workflow }}: [${{ env.github_actor_message }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\n' \
              ${{ env.discord_webhook_url }} | jq; \
          done;

      - name: Send Discord
        if: ${{ false }}
        # Comment:
        # Not doing validate job. Reason in Message from github.
        # Is validate then turn on jobs.
        # 
        # The job was not started because recent account payments have failed or your spending limit needs to be increased.
        # Please check the 'Billing & plans' section in your settings.
        # 
        run: |
          curl_files=''; i=0; for f in github-action-run*; do curl_files=${curl_files}" -F file[$i]=@${f}";i=$((i+1));done;
          for f in github-action-run*; do \
            curl -X POST \
              -H 'Content-Type:multipart/form-data' \
              -F 'avatar_url=${{ env.discord_avatar_url }}' \
              -F 'username=${{ env.discord_username }}' \
              ${curl_files} \
              -F $'content=Launched github action: [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}/actions/workflows/${{ env.github_workflow_ref_name }}).\n${{ github.workflow }}: [${{ env.github_actor_message }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\n' \
              ${{ env.discord_webhook_url }} | jq; \
          done;

      - name: Send Discord
        if: ${{ false }}
        run: |
          for f in github-action-run*; do \
            curl -X POST \
              -H 'Content-Type:multipart/form-data' \
              -F 'payload_json={"avatar_url":"${{ env.discord_avatar_url }}","username":"${{ env.discord_username }}","username":"${{ env.discord_username }}","embeds":[{"color":5793266,"fields":[{"name":"Launched github action","value":"Repository: [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}/actions/workflows/${{ env.github_workflow_ref_name }})."},{"name":"","value":"workflow: ${{ github.workflow }}"},{"name":"","value":"[${{ env.github_actor_message }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"}]}]}' \
              -F "files[0]=@${f}" \
              ${{ env.discord_webhook_url }} | jq; \
          done;

      - name: Send Discord
        run: |
          curl_files=''; i=0; for f in github-action-run*; do curl_files=${curl_files}" -F file[$i]=@${f}";i=$((i+1));done;
          curl -X POST \
            -H 'Content-Type:multipart/form-data' \
            -F 'payload_json={"avatar_url":"${{ env.discord_avatar_url }}","username":"${{ env.discord_username }}","username":"${{ env.discord_username }}","embeds":[{"color":5793266,"fields":[{"name":"Launched github action","value":"Repository: [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}/actions/workflows/${{ env.github_workflow_ref_name }})."},{"name":"","value":"workflow: ${{ github.workflow }}"},{"name":"","value":"[${{ env.github_actor_message }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"}]}]}' \
            ${curl_files} \
            ${{ env.discord_webhook_url }} | jq; \
