name: Get ISO 8601 Date

on:
  workflow_dispatch:
  push:
    paths: 
      - "**.yml"

jobs:
  iso8601:
    runs-on: ubuntu-latest
    steps:
      - name: Set ISO 8601 date as an environment variable
        id: set_date
        run: |
          echo "ISO_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          
      - name: Use the ISO 8601 date variable
        run: |
          echo "::notice title=ISO 8601 Date::The current ISO 8601 date is: ${{ env.ISO_DATE }}"
          echo "The current ISO 8601 date is: ${{ env.ISO_DATE }}"
