name: n138-kz.github.io

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 */2 * *"

permissions:
  contents: read

jobs:
  send_github_context:
    uses: n138-kz/Dockerfile/.github/workflows/github-act_send_github_context.yml@main
    # https://github.com/n138-kz/Dockerfile/blob/main/.github/workflows/github-act_send_github_context.yml
    secrets: inherit # pass all secrets, Require: secrets.DISCORD_WEBHOOK_URL
