name: n138-kz.github.io

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  send_github_context:
    uses: n138-kz/n138-kz.github.io/.github/workflows/github-act_send_github_context.yml@master
    # https://github.com/n138-kz/n138-kz.github.io/blob/master/.github/workflows/github-act_send_github_context.yml
    secrets: inherit # pass all secrets, Require: secrets.DISCORD_WEBHOOK_URL
